# Generated by Django 3.2.6 on 2021-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.CharField(max_length=200, unique=True, verbose_name='회원아이디')),
                ('Mem_pwd', models.CharField(max_length=200, verbose_name='회원비밀번호')),
                ('Mem_name', models.CharField(max_length=200, verbose_name='회원 이름')),
            ],
        ),
    ]
