# Generated by Django 3.2.7 on 2021-09-15 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('pro_price', models.IntegerField(verbose_name='가격')),
                ('pro_stock', models.IntegerField(default=100, verbose_name='재고수량')),
                ('pro_img', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='상품이미지')),
                ('pro_desc', models.TextField(blank=True, verbose_name='상품설명')),
                ('pro_hot', models.BooleanField(default=False, verbose_name='인기상품')),
                ('pro_new', models.BooleanField(default=False, verbose_name='신규상품')),
                ('pro_display', models.BooleanField(default=True, verbose_name='화면표시')),
                ('pro_day', models.DateField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('pro_like', models.IntegerField(default=0)),
            ],
        ),
    ]
