# Generated by Django 3.2.6 on 2021-08-18 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=200, unique=True, verbose_name='도서명')),
                ('Writer', models.CharField(max_length=200, verbose_name='저자')),
                ('Publishing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='출판일')),
                ('Price', models.IntegerField(default=50, verbose_name='가격')),
                ('Intro_book', models.CharField(max_length=200, verbose_name='도서소개')),
            ],
        ),
    ]
