# Generated by Django 3.2.6 on 2021-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_ovew',
            field=models.TextField(default='', null=True),
        ),
    ]
