# Generated by Django 3.2.7 on 2021-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.CharField(max_length=200, unique=True, verbose_name='회원아이디')),
                ('Mem_pwd', models.CharField(max_length=200, verbose_name='회원비밀번호')),
                ('Mem_name', models.CharField(max_length=200, verbose_name='회원 이름')),
                ('Mem_tel', models.CharField(max_length=200, null=True, verbose_name='연락처')),
                ('Mem_addr', models.CharField(max_length=200, null=True, verbose_name='주소')),
                ('Mem_img', models.FileField(blank='True', default='', null=True, upload_to='member/%Y-%m-%d', verbose_name='사진')),
            ],
        ),
    ]
